// Code generated by protoc-gen-go. DO NOT EDIT.
// source: solution/solution.proto

package solution

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// request & response
type SimpleResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SimpleResponse) Reset()         { *m = SimpleResponse{} }
func (m *SimpleResponse) String() string { return proto.CompactTextString(m) }
func (*SimpleResponse) ProtoMessage()    {}
func (*SimpleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0797e02bd350d629, []int{0}
}

func (m *SimpleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimpleResponse.Unmarshal(m, b)
}
func (m *SimpleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimpleResponse.Marshal(b, m, deterministic)
}
func (m *SimpleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimpleResponse.Merge(m, src)
}
func (m *SimpleResponse) XXX_Size() int {
	return xxx_messageInfo_SimpleResponse.Size(m)
}
func (m *SimpleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SimpleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SimpleResponse proto.InternalMessageInfo

func (m *SimpleResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *SimpleResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type SolutionListRequest struct {
	Source               string                   `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	CompanyId            string                   `protobuf:"bytes,2,opt,name=companyId,proto3" json:"companyId,omitempty"`
	AccountId            string                   `protobuf:"bytes,3,opt,name=accountId,proto3" json:"accountId,omitempty"`
	Data                 *SolutionListRequestData `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *SolutionListRequest) Reset()         { *m = SolutionListRequest{} }
func (m *SolutionListRequest) String() string { return proto.CompactTextString(m) }
func (*SolutionListRequest) ProtoMessage()    {}
func (*SolutionListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0797e02bd350d629, []int{1}
}

func (m *SolutionListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SolutionListRequest.Unmarshal(m, b)
}
func (m *SolutionListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SolutionListRequest.Marshal(b, m, deterministic)
}
func (m *SolutionListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SolutionListRequest.Merge(m, src)
}
func (m *SolutionListRequest) XXX_Size() int {
	return xxx_messageInfo_SolutionListRequest.Size(m)
}
func (m *SolutionListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SolutionListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SolutionListRequest proto.InternalMessageInfo

func (m *SolutionListRequest) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *SolutionListRequest) GetCompanyId() string {
	if m != nil {
		return m.CompanyId
	}
	return ""
}

func (m *SolutionListRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *SolutionListRequest) GetData() *SolutionListRequestData {
	if m != nil {
		return m.Data
	}
	return nil
}

type SolutionListResponse struct {
	Code                 int32                     `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string                    `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 *SolutionListResponseData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *SolutionListResponse) Reset()         { *m = SolutionListResponse{} }
func (m *SolutionListResponse) String() string { return proto.CompactTextString(m) }
func (*SolutionListResponse) ProtoMessage()    {}
func (*SolutionListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0797e02bd350d629, []int{2}
}

func (m *SolutionListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SolutionListResponse.Unmarshal(m, b)
}
func (m *SolutionListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SolutionListResponse.Marshal(b, m, deterministic)
}
func (m *SolutionListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SolutionListResponse.Merge(m, src)
}
func (m *SolutionListResponse) XXX_Size() int {
	return xxx_messageInfo_SolutionListResponse.Size(m)
}
func (m *SolutionListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SolutionListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SolutionListResponse proto.InternalMessageInfo

func (m *SolutionListResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *SolutionListResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *SolutionListResponse) GetData() *SolutionListResponseData {
	if m != nil {
		return m.Data
	}
	return nil
}

type SolutionDetailRequest struct {
	Source               string                     `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	CompanyId            string                     `protobuf:"bytes,2,opt,name=companyId,proto3" json:"companyId,omitempty"`
	AccountId            string                     `protobuf:"bytes,3,opt,name=accountId,proto3" json:"accountId,omitempty"`
	Data                 *SolutionDetailRequestData `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *SolutionDetailRequest) Reset()         { *m = SolutionDetailRequest{} }
func (m *SolutionDetailRequest) String() string { return proto.CompactTextString(m) }
func (*SolutionDetailRequest) ProtoMessage()    {}
func (*SolutionDetailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0797e02bd350d629, []int{3}
}

func (m *SolutionDetailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SolutionDetailRequest.Unmarshal(m, b)
}
func (m *SolutionDetailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SolutionDetailRequest.Marshal(b, m, deterministic)
}
func (m *SolutionDetailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SolutionDetailRequest.Merge(m, src)
}
func (m *SolutionDetailRequest) XXX_Size() int {
	return xxx_messageInfo_SolutionDetailRequest.Size(m)
}
func (m *SolutionDetailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SolutionDetailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SolutionDetailRequest proto.InternalMessageInfo

func (m *SolutionDetailRequest) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *SolutionDetailRequest) GetCompanyId() string {
	if m != nil {
		return m.CompanyId
	}
	return ""
}

func (m *SolutionDetailRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *SolutionDetailRequest) GetData() *SolutionDetailRequestData {
	if m != nil {
		return m.Data
	}
	return nil
}

type SolutionDetailResponse struct {
	Code                 int32     `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string    `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 *Solution `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SolutionDetailResponse) Reset()         { *m = SolutionDetailResponse{} }
func (m *SolutionDetailResponse) String() string { return proto.CompactTextString(m) }
func (*SolutionDetailResponse) ProtoMessage()    {}
func (*SolutionDetailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0797e02bd350d629, []int{4}
}

func (m *SolutionDetailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SolutionDetailResponse.Unmarshal(m, b)
}
func (m *SolutionDetailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SolutionDetailResponse.Marshal(b, m, deterministic)
}
func (m *SolutionDetailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SolutionDetailResponse.Merge(m, src)
}
func (m *SolutionDetailResponse) XXX_Size() int {
	return xxx_messageInfo_SolutionDetailResponse.Size(m)
}
func (m *SolutionDetailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SolutionDetailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SolutionDetailResponse proto.InternalMessageInfo

func (m *SolutionDetailResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *SolutionDetailResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *SolutionDetailResponse) GetData() *Solution {
	if m != nil {
		return m.Data
	}
	return nil
}

type SolutionSaveOrUpdateRequest struct {
	Source               string    `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	CompanyId            string    `protobuf:"bytes,2,opt,name=companyId,proto3" json:"companyId,omitempty"`
	AccountId            string    `protobuf:"bytes,3,opt,name=accountId,proto3" json:"accountId,omitempty"`
	Data                 *Solution `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SolutionSaveOrUpdateRequest) Reset()         { *m = SolutionSaveOrUpdateRequest{} }
func (m *SolutionSaveOrUpdateRequest) String() string { return proto.CompactTextString(m) }
func (*SolutionSaveOrUpdateRequest) ProtoMessage()    {}
func (*SolutionSaveOrUpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0797e02bd350d629, []int{5}
}

func (m *SolutionSaveOrUpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SolutionSaveOrUpdateRequest.Unmarshal(m, b)
}
func (m *SolutionSaveOrUpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SolutionSaveOrUpdateRequest.Marshal(b, m, deterministic)
}
func (m *SolutionSaveOrUpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SolutionSaveOrUpdateRequest.Merge(m, src)
}
func (m *SolutionSaveOrUpdateRequest) XXX_Size() int {
	return xxx_messageInfo_SolutionSaveOrUpdateRequest.Size(m)
}
func (m *SolutionSaveOrUpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SolutionSaveOrUpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SolutionSaveOrUpdateRequest proto.InternalMessageInfo

func (m *SolutionSaveOrUpdateRequest) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *SolutionSaveOrUpdateRequest) GetCompanyId() string {
	if m != nil {
		return m.CompanyId
	}
	return ""
}

func (m *SolutionSaveOrUpdateRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *SolutionSaveOrUpdateRequest) GetData() *Solution {
	if m != nil {
		return m.Data
	}
	return nil
}

type SolutionTemplateListRequest struct {
	Source               string                           `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	CompanyId            string                           `protobuf:"bytes,2,opt,name=companyId,proto3" json:"companyId,omitempty"`
	AccountId            string                           `protobuf:"bytes,3,opt,name=accountId,proto3" json:"accountId,omitempty"`
	Data                 *SolutionTemplateListRequestData `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *SolutionTemplateListRequest) Reset()         { *m = SolutionTemplateListRequest{} }
func (m *SolutionTemplateListRequest) String() string { return proto.CompactTextString(m) }
func (*SolutionTemplateListRequest) ProtoMessage()    {}
func (*SolutionTemplateListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0797e02bd350d629, []int{6}
}

func (m *SolutionTemplateListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SolutionTemplateListRequest.Unmarshal(m, b)
}
func (m *SolutionTemplateListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SolutionTemplateListRequest.Marshal(b, m, deterministic)
}
func (m *SolutionTemplateListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SolutionTemplateListRequest.Merge(m, src)
}
func (m *SolutionTemplateListRequest) XXX_Size() int {
	return xxx_messageInfo_SolutionTemplateListRequest.Size(m)
}
func (m *SolutionTemplateListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SolutionTemplateListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SolutionTemplateListRequest proto.InternalMessageInfo

func (m *SolutionTemplateListRequest) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *SolutionTemplateListRequest) GetCompanyId() string {
	if m != nil {
		return m.CompanyId
	}
	return ""
}

func (m *SolutionTemplateListRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *SolutionTemplateListRequest) GetData() *SolutionTemplateListRequestData {
	if m != nil {
		return m.Data
	}
	return nil
}

type SolutionTemplateListResponse struct {
	Code                 int32                             `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string                            `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 *SolutionTemplateListResponseData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *SolutionTemplateListResponse) Reset()         { *m = SolutionTemplateListResponse{} }
func (m *SolutionTemplateListResponse) String() string { return proto.CompactTextString(m) }
func (*SolutionTemplateListResponse) ProtoMessage()    {}
func (*SolutionTemplateListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0797e02bd350d629, []int{7}
}

func (m *SolutionTemplateListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SolutionTemplateListResponse.Unmarshal(m, b)
}
func (m *SolutionTemplateListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SolutionTemplateListResponse.Marshal(b, m, deterministic)
}
func (m *SolutionTemplateListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SolutionTemplateListResponse.Merge(m, src)
}
func (m *SolutionTemplateListResponse) XXX_Size() int {
	return xxx_messageInfo_SolutionTemplateListResponse.Size(m)
}
func (m *SolutionTemplateListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SolutionTemplateListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SolutionTemplateListResponse proto.InternalMessageInfo

func (m *SolutionTemplateListResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *SolutionTemplateListResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *SolutionTemplateListResponse) GetData() *SolutionTemplateListResponseData {
	if m != nil {
		return m.Data
	}
	return nil
}

type SolutionTemplateDetailRequest struct {
	Source               string                             `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	CompanyId            string                             `protobuf:"bytes,2,opt,name=companyId,proto3" json:"companyId,omitempty"`
	AccountId            string                             `protobuf:"bytes,3,opt,name=accountId,proto3" json:"accountId,omitempty"`
	Data                 *SolutionTemplateDetailRequestData `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                           `json:"-"`
	XXX_unrecognized     []byte                             `json:"-"`
	XXX_sizecache        int32                              `json:"-"`
}

func (m *SolutionTemplateDetailRequest) Reset()         { *m = SolutionTemplateDetailRequest{} }
func (m *SolutionTemplateDetailRequest) String() string { return proto.CompactTextString(m) }
func (*SolutionTemplateDetailRequest) ProtoMessage()    {}
func (*SolutionTemplateDetailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0797e02bd350d629, []int{8}
}

func (m *SolutionTemplateDetailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SolutionTemplateDetailRequest.Unmarshal(m, b)
}
func (m *SolutionTemplateDetailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SolutionTemplateDetailRequest.Marshal(b, m, deterministic)
}
func (m *SolutionTemplateDetailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SolutionTemplateDetailRequest.Merge(m, src)
}
func (m *SolutionTemplateDetailRequest) XXX_Size() int {
	return xxx_messageInfo_SolutionTemplateDetailRequest.Size(m)
}
func (m *SolutionTemplateDetailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SolutionTemplateDetailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SolutionTemplateDetailRequest proto.InternalMessageInfo

func (m *SolutionTemplateDetailRequest) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *SolutionTemplateDetailRequest) GetCompanyId() string {
	if m != nil {
		return m.CompanyId
	}
	return ""
}

func (m *SolutionTemplateDetailRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *SolutionTemplateDetailRequest) GetData() *SolutionTemplateDetailRequestData {
	if m != nil {
		return m.Data
	}
	return nil
}

type SolutionTemplateDetailResponse struct {
	Code                 int32     `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string    `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 *Template `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SolutionTemplateDetailResponse) Reset()         { *m = SolutionTemplateDetailResponse{} }
func (m *SolutionTemplateDetailResponse) String() string { return proto.CompactTextString(m) }
func (*SolutionTemplateDetailResponse) ProtoMessage()    {}
func (*SolutionTemplateDetailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0797e02bd350d629, []int{9}
}

func (m *SolutionTemplateDetailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SolutionTemplateDetailResponse.Unmarshal(m, b)
}
func (m *SolutionTemplateDetailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SolutionTemplateDetailResponse.Marshal(b, m, deterministic)
}
func (m *SolutionTemplateDetailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SolutionTemplateDetailResponse.Merge(m, src)
}
func (m *SolutionTemplateDetailResponse) XXX_Size() int {
	return xxx_messageInfo_SolutionTemplateDetailResponse.Size(m)
}
func (m *SolutionTemplateDetailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SolutionTemplateDetailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SolutionTemplateDetailResponse proto.InternalMessageInfo

func (m *SolutionTemplateDetailResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *SolutionTemplateDetailResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *SolutionTemplateDetailResponse) GetData() *Template {
	if m != nil {
		return m.Data
	}
	return nil
}

type SolutionListRequestData struct {
	SolutionIds          []string `protobuf:"bytes,1,rep,name=solutionIds,proto3" json:"solutionIds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SolutionListRequestData) Reset()         { *m = SolutionListRequestData{} }
func (m *SolutionListRequestData) String() string { return proto.CompactTextString(m) }
func (*SolutionListRequestData) ProtoMessage()    {}
func (*SolutionListRequestData) Descriptor() ([]byte, []int) {
	return fileDescriptor_0797e02bd350d629, []int{10}
}

func (m *SolutionListRequestData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SolutionListRequestData.Unmarshal(m, b)
}
func (m *SolutionListRequestData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SolutionListRequestData.Marshal(b, m, deterministic)
}
func (m *SolutionListRequestData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SolutionListRequestData.Merge(m, src)
}
func (m *SolutionListRequestData) XXX_Size() int {
	return xxx_messageInfo_SolutionListRequestData.Size(m)
}
func (m *SolutionListRequestData) XXX_DiscardUnknown() {
	xxx_messageInfo_SolutionListRequestData.DiscardUnknown(m)
}

var xxx_messageInfo_SolutionListRequestData proto.InternalMessageInfo

func (m *SolutionListRequestData) GetSolutionIds() []string {
	if m != nil {
		return m.SolutionIds
	}
	return nil
}

type SolutionDetailRequestData struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SolutionDetailRequestData) Reset()         { *m = SolutionDetailRequestData{} }
func (m *SolutionDetailRequestData) String() string { return proto.CompactTextString(m) }
func (*SolutionDetailRequestData) ProtoMessage()    {}
func (*SolutionDetailRequestData) Descriptor() ([]byte, []int) {
	return fileDescriptor_0797e02bd350d629, []int{11}
}

func (m *SolutionDetailRequestData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SolutionDetailRequestData.Unmarshal(m, b)
}
func (m *SolutionDetailRequestData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SolutionDetailRequestData.Marshal(b, m, deterministic)
}
func (m *SolutionDetailRequestData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SolutionDetailRequestData.Merge(m, src)
}
func (m *SolutionDetailRequestData) XXX_Size() int {
	return xxx_messageInfo_SolutionDetailRequestData.Size(m)
}
func (m *SolutionDetailRequestData) XXX_DiscardUnknown() {
	xxx_messageInfo_SolutionDetailRequestData.DiscardUnknown(m)
}

var xxx_messageInfo_SolutionDetailRequestData proto.InternalMessageInfo

func (m *SolutionDetailRequestData) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type SolutionTemplateListRequestData struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SolutionTemplateListRequestData) Reset()         { *m = SolutionTemplateListRequestData{} }
func (m *SolutionTemplateListRequestData) String() string { return proto.CompactTextString(m) }
func (*SolutionTemplateListRequestData) ProtoMessage()    {}
func (*SolutionTemplateListRequestData) Descriptor() ([]byte, []int) {
	return fileDescriptor_0797e02bd350d629, []int{12}
}

func (m *SolutionTemplateListRequestData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SolutionTemplateListRequestData.Unmarshal(m, b)
}
func (m *SolutionTemplateListRequestData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SolutionTemplateListRequestData.Marshal(b, m, deterministic)
}
func (m *SolutionTemplateListRequestData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SolutionTemplateListRequestData.Merge(m, src)
}
func (m *SolutionTemplateListRequestData) XXX_Size() int {
	return xxx_messageInfo_SolutionTemplateListRequestData.Size(m)
}
func (m *SolutionTemplateListRequestData) XXX_DiscardUnknown() {
	xxx_messageInfo_SolutionTemplateListRequestData.DiscardUnknown(m)
}

var xxx_messageInfo_SolutionTemplateListRequestData proto.InternalMessageInfo

func (m *SolutionTemplateListRequestData) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type SolutionListResponseData struct {
	Items                []*Solution `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SolutionListResponseData) Reset()         { *m = SolutionListResponseData{} }
func (m *SolutionListResponseData) String() string { return proto.CompactTextString(m) }
func (*SolutionListResponseData) ProtoMessage()    {}
func (*SolutionListResponseData) Descriptor() ([]byte, []int) {
	return fileDescriptor_0797e02bd350d629, []int{13}
}

func (m *SolutionListResponseData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SolutionListResponseData.Unmarshal(m, b)
}
func (m *SolutionListResponseData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SolutionListResponseData.Marshal(b, m, deterministic)
}
func (m *SolutionListResponseData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SolutionListResponseData.Merge(m, src)
}
func (m *SolutionListResponseData) XXX_Size() int {
	return xxx_messageInfo_SolutionListResponseData.Size(m)
}
func (m *SolutionListResponseData) XXX_DiscardUnknown() {
	xxx_messageInfo_SolutionListResponseData.DiscardUnknown(m)
}

var xxx_messageInfo_SolutionListResponseData proto.InternalMessageInfo

func (m *SolutionListResponseData) GetItems() []*Solution {
	if m != nil {
		return m.Items
	}
	return nil
}

type SolutionTemplateListResponseData struct {
	Items                []*Template `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SolutionTemplateListResponseData) Reset()         { *m = SolutionTemplateListResponseData{} }
func (m *SolutionTemplateListResponseData) String() string { return proto.CompactTextString(m) }
func (*SolutionTemplateListResponseData) ProtoMessage()    {}
func (*SolutionTemplateListResponseData) Descriptor() ([]byte, []int) {
	return fileDescriptor_0797e02bd350d629, []int{14}
}

func (m *SolutionTemplateListResponseData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SolutionTemplateListResponseData.Unmarshal(m, b)
}
func (m *SolutionTemplateListResponseData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SolutionTemplateListResponseData.Marshal(b, m, deterministic)
}
func (m *SolutionTemplateListResponseData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SolutionTemplateListResponseData.Merge(m, src)
}
func (m *SolutionTemplateListResponseData) XXX_Size() int {
	return xxx_messageInfo_SolutionTemplateListResponseData.Size(m)
}
func (m *SolutionTemplateListResponseData) XXX_DiscardUnknown() {
	xxx_messageInfo_SolutionTemplateListResponseData.DiscardUnknown(m)
}

var xxx_messageInfo_SolutionTemplateListResponseData proto.InternalMessageInfo

func (m *SolutionTemplateListResponseData) GetItems() []*Template {
	if m != nil {
		return m.Items
	}
	return nil
}

type SolutionTemplateDetailRequestData struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SolutionTemplateDetailRequestData) Reset()         { *m = SolutionTemplateDetailRequestData{} }
func (m *SolutionTemplateDetailRequestData) String() string { return proto.CompactTextString(m) }
func (*SolutionTemplateDetailRequestData) ProtoMessage()    {}
func (*SolutionTemplateDetailRequestData) Descriptor() ([]byte, []int) {
	return fileDescriptor_0797e02bd350d629, []int{15}
}

func (m *SolutionTemplateDetailRequestData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SolutionTemplateDetailRequestData.Unmarshal(m, b)
}
func (m *SolutionTemplateDetailRequestData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SolutionTemplateDetailRequestData.Marshal(b, m, deterministic)
}
func (m *SolutionTemplateDetailRequestData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SolutionTemplateDetailRequestData.Merge(m, src)
}
func (m *SolutionTemplateDetailRequestData) XXX_Size() int {
	return xxx_messageInfo_SolutionTemplateDetailRequestData.Size(m)
}
func (m *SolutionTemplateDetailRequestData) XXX_DiscardUnknown() {
	xxx_messageInfo_SolutionTemplateDetailRequestData.DiscardUnknown(m)
}

var xxx_messageInfo_SolutionTemplateDetailRequestData proto.InternalMessageInfo

func (m *SolutionTemplateDetailRequestData) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Solution struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	No string `protobuf:"bytes,2,opt,name=no,proto3" json:"no,omitempty"`
	// @inject_tag: bson:"companyId"
	CompanyId string `protobuf:"bytes,3,opt,name=companyId,proto3" json:"companyId,omitempty"`
	Name      string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	// @inject_tag: bson:"innerName"
	InnerName string    `protobuf:"bytes,5,opt,name=innerName,proto3" json:"innerName,omitempty"`
	Type      string    `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	Domains   []*Domain `protobuf:"bytes,7,rep,name=domains,proto3" json:"domains,omitempty"`
	// @inject_tag: bson:"viewId"
	ViewId string `protobuf:"bytes,8,opt,name=viewId,proto3" json:"viewId,omitempty"`
	// @inject_tag: bson:"mobilePreviewImage"
	MobilePreviewImage string `protobuf:"bytes,9,opt,name=mobilePreviewImage,proto3" json:"mobilePreviewImage,omitempty"`
	// @inject_tag: bson:"pcPreviewImage"
	PcPreviewImage string `protobuf:"bytes,10,opt,name=pcPreviewImage,proto3" json:"pcPreviewImage,omitempty"`
	Thumbnail      string `protobuf:"bytes,11,opt,name=thumbnail,proto3" json:"thumbnail,omitempty"`
	// @inject_tag: bson:"templateId"
	TemplateId string `protobuf:"bytes,12,opt,name=templateId,proto3" json:"templateId,omitempty"`
	// @inject_tag: bson:"paymentTypes"
	PaymentTypes []string `protobuf:"bytes,13,rep,name=paymentTypes,proto3" json:"paymentTypes,omitempty"`
	// @inject_tag: bson:"domainCertificate"
	DomainCertificate string `protobuf:"bytes,14,opt,name=domainCertificate,proto3" json:"domainCertificate,omitempty"`
	// @inject_tag: bson:"isSSL"
	IsSSL    bool   `protobuf:"varint,15,opt,name=isSSL,proto3" json:"isSSL,omitempty"`
	Logo     string `protobuf:"bytes,16,opt,name=logo,proto3" json:"logo,omitempty"`
	Status   string `protobuf:"bytes,17,opt,name=status,proto3" json:"status,omitempty"`
	Language string `protobuf:"bytes,18,opt,name=language,proto3" json:"language,omitempty"`
	// @inject_tag: bson:"currencyCode"
	CurrencyCode string `protobuf:"bytes,19,opt,name=currencyCode,proto3" json:"currencyCode,omitempty"`
	// @inject_tag: bson:"currencySymbol"
	CurrencySymbol string `protobuf:"bytes,20,opt,name=currencySymbol,proto3" json:"currencySymbol,omitempty"`
	// @inject_tag: bson:"createTime"
	CreateTime string `protobuf:"bytes,21,opt,name=createTime,proto3" json:"createTime,omitempty"`
	// @inject_tag: bson:"updateTime"
	UpdateTime string `protobuf:"bytes,22,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	// @inject_tag: bson:"platformSolutionToken"
	PlatformSolutionToken string `protobuf:"bytes,23,opt,name=platformSolutionToken,proto3" json:"platformSolutionToken,omitempty"`
	// @inject_tag: bson:"platformSolutionId"
	PlatformSolutionId string `protobuf:"bytes,24,opt,name=platformSolutionId,proto3" json:"platformSolutionId,omitempty"`
	// @inject_tag: bson:"platformSolutionName"
	PlatformSolutionName string `protobuf:"bytes,25,opt,name=platformSolutionName,proto3" json:"platformSolutionName,omitempty"`
	// @inject_tag: bson:"platformName"
	PlatformName string `protobuf:"bytes,26,opt,name=platformName,proto3" json:"platformName,omitempty"`
	// @inject_tag: bson:"singlePageConfig"
	SinglePageConfig     *SinglePageConfig `protobuf:"bytes,27,opt,name=singlePageConfig,proto3" json:"singlePageConfig,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Solution) Reset()         { *m = Solution{} }
func (m *Solution) String() string { return proto.CompactTextString(m) }
func (*Solution) ProtoMessage()    {}
func (*Solution) Descriptor() ([]byte, []int) {
	return fileDescriptor_0797e02bd350d629, []int{16}
}

func (m *Solution) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Solution.Unmarshal(m, b)
}
func (m *Solution) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Solution.Marshal(b, m, deterministic)
}
func (m *Solution) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Solution.Merge(m, src)
}
func (m *Solution) XXX_Size() int {
	return xxx_messageInfo_Solution.Size(m)
}
func (m *Solution) XXX_DiscardUnknown() {
	xxx_messageInfo_Solution.DiscardUnknown(m)
}

var xxx_messageInfo_Solution proto.InternalMessageInfo

func (m *Solution) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Solution) GetNo() string {
	if m != nil {
		return m.No
	}
	return ""
}

func (m *Solution) GetCompanyId() string {
	if m != nil {
		return m.CompanyId
	}
	return ""
}

func (m *Solution) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Solution) GetInnerName() string {
	if m != nil {
		return m.InnerName
	}
	return ""
}

func (m *Solution) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Solution) GetDomains() []*Domain {
	if m != nil {
		return m.Domains
	}
	return nil
}

func (m *Solution) GetViewId() string {
	if m != nil {
		return m.ViewId
	}
	return ""
}

func (m *Solution) GetMobilePreviewImage() string {
	if m != nil {
		return m.MobilePreviewImage
	}
	return ""
}

func (m *Solution) GetPcPreviewImage() string {
	if m != nil {
		return m.PcPreviewImage
	}
	return ""
}

func (m *Solution) GetThumbnail() string {
	if m != nil {
		return m.Thumbnail
	}
	return ""
}

func (m *Solution) GetTemplateId() string {
	if m != nil {
		return m.TemplateId
	}
	return ""
}

func (m *Solution) GetPaymentTypes() []string {
	if m != nil {
		return m.PaymentTypes
	}
	return nil
}

func (m *Solution) GetDomainCertificate() string {
	if m != nil {
		return m.DomainCertificate
	}
	return ""
}

func (m *Solution) GetIsSSL() bool {
	if m != nil {
		return m.IsSSL
	}
	return false
}

func (m *Solution) GetLogo() string {
	if m != nil {
		return m.Logo
	}
	return ""
}

func (m *Solution) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Solution) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *Solution) GetCurrencyCode() string {
	if m != nil {
		return m.CurrencyCode
	}
	return ""
}

func (m *Solution) GetCurrencySymbol() string {
	if m != nil {
		return m.CurrencySymbol
	}
	return ""
}

func (m *Solution) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *Solution) GetUpdateTime() string {
	if m != nil {
		return m.UpdateTime
	}
	return ""
}

func (m *Solution) GetPlatformSolutionToken() string {
	if m != nil {
		return m.PlatformSolutionToken
	}
	return ""
}

func (m *Solution) GetPlatformSolutionId() string {
	if m != nil {
		return m.PlatformSolutionId
	}
	return ""
}

func (m *Solution) GetPlatformSolutionName() string {
	if m != nil {
		return m.PlatformSolutionName
	}
	return ""
}

func (m *Solution) GetPlatformName() string {
	if m != nil {
		return m.PlatformName
	}
	return ""
}

func (m *Solution) GetSinglePageConfig() *SinglePageConfig {
	if m != nil {
		return m.SinglePageConfig
	}
	return nil
}

type Domain struct {
	Domain               string   `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Domain) Reset()         { *m = Domain{} }
func (m *Domain) String() string { return proto.CompactTextString(m) }
func (*Domain) ProtoMessage()    {}
func (*Domain) Descriptor() ([]byte, []int) {
	return fileDescriptor_0797e02bd350d629, []int{17}
}

func (m *Domain) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Domain.Unmarshal(m, b)
}
func (m *Domain) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Domain.Marshal(b, m, deterministic)
}
func (m *Domain) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Domain.Merge(m, src)
}
func (m *Domain) XXX_Size() int {
	return xxx_messageInfo_Domain.Size(m)
}
func (m *Domain) XXX_DiscardUnknown() {
	xxx_messageInfo_Domain.DiscardUnknown(m)
}

var xxx_messageInfo_Domain proto.InternalMessageInfo

func (m *Domain) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *Domain) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type SinglePageConfig struct {
	ProductId string `protobuf:"bytes,1,opt,name=productId,proto3" json:"productId,omitempty"`
	// @inject_tag: bson:"customFunctions"
	CustomFunctions []string `protobuf:"bytes,2,rep,name=customFunctions,proto3" json:"customFunctions,omitempty"`
	// @inject_tag: bson:"markingConfig"
	MarkingConfig        *MarkingConfig `protobuf:"bytes,3,opt,name=markingConfig,proto3" json:"markingConfig,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SinglePageConfig) Reset()         { *m = SinglePageConfig{} }
func (m *SinglePageConfig) String() string { return proto.CompactTextString(m) }
func (*SinglePageConfig) ProtoMessage()    {}
func (*SinglePageConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_0797e02bd350d629, []int{18}
}

func (m *SinglePageConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SinglePageConfig.Unmarshal(m, b)
}
func (m *SinglePageConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SinglePageConfig.Marshal(b, m, deterministic)
}
func (m *SinglePageConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SinglePageConfig.Merge(m, src)
}
func (m *SinglePageConfig) XXX_Size() int {
	return xxx_messageInfo_SinglePageConfig.Size(m)
}
func (m *SinglePageConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_SinglePageConfig.DiscardUnknown(m)
}

var xxx_messageInfo_SinglePageConfig proto.InternalMessageInfo

func (m *SinglePageConfig) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

func (m *SinglePageConfig) GetCustomFunctions() []string {
	if m != nil {
		return m.CustomFunctions
	}
	return nil
}

func (m *SinglePageConfig) GetMarkingConfig() *MarkingConfig {
	if m != nil {
		return m.MarkingConfig
	}
	return nil
}

type MarkingConfig struct {
	// @inject_tag: bson:"timeCount"
	TimeCount *TimeCount `protobuf:"bytes,1,opt,name=timeCount,proto3" json:"timeCount,omitempty"`
	// @inject_tag: bson:"groupPurchase"
	GroupPurchase *GroupPurchase `protobuf:"bytes,2,opt,name=groupPurchase,proto3" json:"groupPurchase,omitempty"`
	// @inject_tag: bson:"fullReduction"
	FullReduction        *FullReduction `protobuf:"bytes,3,opt,name=fullReduction,proto3" json:"fullReduction,omitempty"`
	Judgement            string         `protobuf:"bytes,4,opt,name=judgement,proto3" json:"judgement,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *MarkingConfig) Reset()         { *m = MarkingConfig{} }
func (m *MarkingConfig) String() string { return proto.CompactTextString(m) }
func (*MarkingConfig) ProtoMessage()    {}
func (*MarkingConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_0797e02bd350d629, []int{19}
}

func (m *MarkingConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MarkingConfig.Unmarshal(m, b)
}
func (m *MarkingConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MarkingConfig.Marshal(b, m, deterministic)
}
func (m *MarkingConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarkingConfig.Merge(m, src)
}
func (m *MarkingConfig) XXX_Size() int {
	return xxx_messageInfo_MarkingConfig.Size(m)
}
func (m *MarkingConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_MarkingConfig.DiscardUnknown(m)
}

var xxx_messageInfo_MarkingConfig proto.InternalMessageInfo

func (m *MarkingConfig) GetTimeCount() *TimeCount {
	if m != nil {
		return m.TimeCount
	}
	return nil
}

func (m *MarkingConfig) GetGroupPurchase() *GroupPurchase {
	if m != nil {
		return m.GroupPurchase
	}
	return nil
}

func (m *MarkingConfig) GetFullReduction() *FullReduction {
	if m != nil {
		return m.FullReduction
	}
	return nil
}

func (m *MarkingConfig) GetJudgement() string {
	if m != nil {
		return m.Judgement
	}
	return ""
}

type TimeCount struct {
	// @inject_tag: bson:"durationSecond"
	DurationSecond int64 `protobuf:"varint,1,opt,name=durationSecond,proto3" json:"durationSecond,omitempty"`
	// @inject_tag: bson:"productTotal"
	ProductTotal int64 `protobuf:"varint,2,opt,name=productTotal,proto3" json:"productTotal,omitempty"`
	// @inject_tag: bson:"productSold"
	ProductSold int64 `protobuf:"varint,3,opt,name=productSold,proto3" json:"productSold,omitempty"`
	// @inject_tag: bson:"hoursToAddSold"
	HoursToAddSold int64 `protobuf:"varint,4,opt,name=hoursToAddSold,proto3" json:"hoursToAddSold,omitempty"`
	// @inject_tag: bson:"productToAddSold"
	ProductToAddSold int64 `protobuf:"varint,5,opt,name=productToAddSold,proto3" json:"productToAddSold,omitempty"`
	// @inject_tag: bson:"hoursToRecover"
	HoursToRecover       int64    `protobuf:"varint,6,opt,name=hoursToRecover,proto3" json:"hoursToRecover,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TimeCount) Reset()         { *m = TimeCount{} }
func (m *TimeCount) String() string { return proto.CompactTextString(m) }
func (*TimeCount) ProtoMessage()    {}
func (*TimeCount) Descriptor() ([]byte, []int) {
	return fileDescriptor_0797e02bd350d629, []int{20}
}

func (m *TimeCount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeCount.Unmarshal(m, b)
}
func (m *TimeCount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeCount.Marshal(b, m, deterministic)
}
func (m *TimeCount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeCount.Merge(m, src)
}
func (m *TimeCount) XXX_Size() int {
	return xxx_messageInfo_TimeCount.Size(m)
}
func (m *TimeCount) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeCount.DiscardUnknown(m)
}

var xxx_messageInfo_TimeCount proto.InternalMessageInfo

func (m *TimeCount) GetDurationSecond() int64 {
	if m != nil {
		return m.DurationSecond
	}
	return 0
}

func (m *TimeCount) GetProductTotal() int64 {
	if m != nil {
		return m.ProductTotal
	}
	return 0
}

func (m *TimeCount) GetProductSold() int64 {
	if m != nil {
		return m.ProductSold
	}
	return 0
}

func (m *TimeCount) GetHoursToAddSold() int64 {
	if m != nil {
		return m.HoursToAddSold
	}
	return 0
}

func (m *TimeCount) GetProductToAddSold() int64 {
	if m != nil {
		return m.ProductToAddSold
	}
	return 0
}

func (m *TimeCount) GetHoursToRecover() int64 {
	if m != nil {
		return m.HoursToRecover
	}
	return 0
}

type GroupPurchase struct {
	Members              int64    `protobuf:"varint,1,opt,name=members,proto3" json:"members,omitempty"`
	Reduction            int64    `protobuf:"varint,2,opt,name=reduction,proto3" json:"reduction,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupPurchase) Reset()         { *m = GroupPurchase{} }
func (m *GroupPurchase) String() string { return proto.CompactTextString(m) }
func (*GroupPurchase) ProtoMessage()    {}
func (*GroupPurchase) Descriptor() ([]byte, []int) {
	return fileDescriptor_0797e02bd350d629, []int{21}
}

func (m *GroupPurchase) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupPurchase.Unmarshal(m, b)
}
func (m *GroupPurchase) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupPurchase.Marshal(b, m, deterministic)
}
func (m *GroupPurchase) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupPurchase.Merge(m, src)
}
func (m *GroupPurchase) XXX_Size() int {
	return xxx_messageInfo_GroupPurchase.Size(m)
}
func (m *GroupPurchase) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupPurchase.DiscardUnknown(m)
}

var xxx_messageInfo_GroupPurchase proto.InternalMessageInfo

func (m *GroupPurchase) GetMembers() int64 {
	if m != nil {
		return m.Members
	}
	return 0
}

func (m *GroupPurchase) GetReduction() int64 {
	if m != nil {
		return m.Reduction
	}
	return 0
}

type FullReduction struct {
	// @inject_tag: bson:"amountToReduction"
	AmountToReduction    int64    `protobuf:"varint,1,opt,name=amountToReduction,proto3" json:"amountToReduction,omitempty"`
	Reduction            int64    `protobuf:"varint,2,opt,name=reduction,proto3" json:"reduction,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FullReduction) Reset()         { *m = FullReduction{} }
func (m *FullReduction) String() string { return proto.CompactTextString(m) }
func (*FullReduction) ProtoMessage()    {}
func (*FullReduction) Descriptor() ([]byte, []int) {
	return fileDescriptor_0797e02bd350d629, []int{22}
}

func (m *FullReduction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FullReduction.Unmarshal(m, b)
}
func (m *FullReduction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FullReduction.Marshal(b, m, deterministic)
}
func (m *FullReduction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FullReduction.Merge(m, src)
}
func (m *FullReduction) XXX_Size() int {
	return xxx_messageInfo_FullReduction.Size(m)
}
func (m *FullReduction) XXX_DiscardUnknown() {
	xxx_messageInfo_FullReduction.DiscardUnknown(m)
}

var xxx_messageInfo_FullReduction proto.InternalMessageInfo

func (m *FullReduction) GetAmountToReduction() int64 {
	if m != nil {
		return m.AmountToReduction
	}
	return 0
}

func (m *FullReduction) GetReduction() int64 {
	if m != nil {
		return m.Reduction
	}
	return 0
}

type Template struct {
	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Desc string `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`
	Type string `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	// @inject_tag: bson:"pcPreviewImage"
	PcPreviewImage string `protobuf:"bytes,5,opt,name=pcPreviewImage,proto3" json:"pcPreviewImage,omitempty"`
	// @inject_tag: bson:"mobilePreviewImage"
	MobilePreviewImage string `protobuf:"bytes,6,opt,name=mobilePreviewImage,proto3" json:"mobilePreviewImage,omitempty"`
	Thumbnail          string `protobuf:"bytes,7,opt,name=thumbnail,proto3" json:"thumbnail,omitempty"`
	// @inject_tag: bson:"listImage"
	ListImage string   `protobuf:"bytes,8,opt,name=listImage,proto3" json:"listImage,omitempty"`
	Languages []string `protobuf:"bytes,9,rep,name=languages,proto3" json:"languages,omitempty"`
	// @inject_tag: bson:"isFree"
	IsFree               bool            `protobuf:"varint,10,opt,name=isFree,proto3" json:"isFree,omitempty"`
	Config               *TemplateConfig `protobuf:"bytes,11,opt,name=config,proto3" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Template) Reset()         { *m = Template{} }
func (m *Template) String() string { return proto.CompactTextString(m) }
func (*Template) ProtoMessage()    {}
func (*Template) Descriptor() ([]byte, []int) {
	return fileDescriptor_0797e02bd350d629, []int{23}
}

func (m *Template) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Template.Unmarshal(m, b)
}
func (m *Template) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Template.Marshal(b, m, deterministic)
}
func (m *Template) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Template.Merge(m, src)
}
func (m *Template) XXX_Size() int {
	return xxx_messageInfo_Template.Size(m)
}
func (m *Template) XXX_DiscardUnknown() {
	xxx_messageInfo_Template.DiscardUnknown(m)
}

var xxx_messageInfo_Template proto.InternalMessageInfo

func (m *Template) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Template) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Template) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *Template) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Template) GetPcPreviewImage() string {
	if m != nil {
		return m.PcPreviewImage
	}
	return ""
}

func (m *Template) GetMobilePreviewImage() string {
	if m != nil {
		return m.MobilePreviewImage
	}
	return ""
}

func (m *Template) GetThumbnail() string {
	if m != nil {
		return m.Thumbnail
	}
	return ""
}

func (m *Template) GetListImage() string {
	if m != nil {
		return m.ListImage
	}
	return ""
}

func (m *Template) GetLanguages() []string {
	if m != nil {
		return m.Languages
	}
	return nil
}

func (m *Template) GetIsFree() bool {
	if m != nil {
		return m.IsFree
	}
	return false
}

func (m *Template) GetConfig() *TemplateConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

type TemplateConfig struct {
	// @inject_tag: bson:"hasLogo"
	HasLogo bool `protobuf:"varint,1,opt,name=hasLogo,proto3" json:"hasLogo,omitempty"`
	// @inject_tag: bson:"hasDomain"
	HasDomain bool `protobuf:"varint,2,opt,name=hasDomain,proto3" json:"hasDomain,omitempty"`
	// @inject_tag: bson:"hasPaymentType"
	HasPaymentType bool `protobuf:"varint,3,opt,name=hasPaymentType,proto3" json:"hasPaymentType,omitempty"`
	// @inject_tag: bson:"hasCountry"
	HasCountry bool `protobuf:"varint,4,opt,name=hasCountry,proto3" json:"hasCountry,omitempty"`
	// @inject_tag: bson:"hasBrandSiteModules"
	HasBrandSiteModules bool `protobuf:"varint,5,opt,name=hasBrandSiteModules,proto3" json:"hasBrandSiteModules,omitempty"`
	// @inject_tag: bson:"hasDemand"
	HasDemand bool `protobuf:"varint,6,opt,name=hasDemand,proto3" json:"hasDemand,omitempty"`
	// @inject_tag: bson:"hasContact"
	HasContact bool `protobuf:"varint,7,opt,name=hasContact,proto3" json:"hasContact,omitempty"`
	// @inject_tag: bson:"hasSinglePageCustomFunctions"
	HasSinglePageCustomFunctions bool `protobuf:"varint,8,opt,name=hasSinglePageCustomFunctions,proto3" json:"hasSinglePageCustomFunctions,omitempty"`
	// @inject_tag: bson:"hasBrandSiteCustomFunctions"
	HasBrandSiteCustomFunctions bool `protobuf:"varint,9,opt,name=hasBrandSiteCustomFunctions,proto3" json:"hasBrandSiteCustomFunctions,omitempty"`
	// @inject_tag: bson:"hasMallCustomFunctions"
	HasMallCustomFunctions bool `protobuf:"varint,10,opt,name=hasMallCustomFunctions,proto3" json:"hasMallCustomFunctions,omitempty"`
	// @inject_tag: bson:"hasAppCustomFunctions"
	HasAppCustomFunctions bool `protobuf:"varint,11,opt,name=hasAppCustomFunctions,proto3" json:"hasAppCustomFunctions,omitempty"`
	// @inject_tag: bson:"hasSinglePageProduct"
	HasSinglePageProduct bool `protobuf:"varint,12,opt,name=hasSinglePageProduct,proto3" json:"hasSinglePageProduct,omitempty"`
	// @inject_tag: bson:"hasSinglePageMarkingTimeCount"
	HasSinglePageMarkingTimeCount bool `protobuf:"varint,13,opt,name=hasSinglePageMarkingTimeCount,proto3" json:"hasSinglePageMarkingTimeCount,omitempty"`
	// @inject_tag: bson:"hasSinglePageMarkingGroupPurchase"
	HasSinglePageMarkingGroupPurchase bool `protobuf:"varint,14,opt,name=hasSinglePageMarkingGroupPurchase,proto3" json:"hasSinglePageMarkingGroupPurchase,omitempty"`
	// @inject_tag: bson:"hasSinglePageMarkingFullReduction"
	HasSinglePageMarkingFullReduction bool `protobuf:"varint,15,opt,name=hasSinglePageMarkingFullReduction,proto3" json:"hasSinglePageMarkingFullReduction,omitempty"`
	// @inject_tag: bson:"hasSinglePageMarkingJudgement"
	HasSinglePageMarkingJudgement bool `protobuf:"varint,16,opt,name=hasSinglePageMarkingJudgement,proto3" json:"hasSinglePageMarkingJudgement,omitempty"`
	// @inject_tag: bson:"hasLanguage"
	HasLanguage bool `protobuf:"varint,17,opt,name=hasLanguage,proto3" json:"hasLanguage,omitempty"`
	// @inject_tag: bson:"hasCurrency"
	HasCurrency bool `protobuf:"varint,18,opt,name=hasCurrency,proto3" json:"hasCurrency,omitempty"`
	// @inject_tag: bson:"hasDomains"
	HasDomains           bool     `protobuf:"varint,19,opt,name=hasDomains,proto3" json:"hasDomains,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TemplateConfig) Reset()         { *m = TemplateConfig{} }
func (m *TemplateConfig) String() string { return proto.CompactTextString(m) }
func (*TemplateConfig) ProtoMessage()    {}
func (*TemplateConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_0797e02bd350d629, []int{24}
}

func (m *TemplateConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TemplateConfig.Unmarshal(m, b)
}
func (m *TemplateConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TemplateConfig.Marshal(b, m, deterministic)
}
func (m *TemplateConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TemplateConfig.Merge(m, src)
}
func (m *TemplateConfig) XXX_Size() int {
	return xxx_messageInfo_TemplateConfig.Size(m)
}
func (m *TemplateConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_TemplateConfig.DiscardUnknown(m)
}

var xxx_messageInfo_TemplateConfig proto.InternalMessageInfo

func (m *TemplateConfig) GetHasLogo() bool {
	if m != nil {
		return m.HasLogo
	}
	return false
}

func (m *TemplateConfig) GetHasDomain() bool {
	if m != nil {
		return m.HasDomain
	}
	return false
}

func (m *TemplateConfig) GetHasPaymentType() bool {
	if m != nil {
		return m.HasPaymentType
	}
	return false
}

func (m *TemplateConfig) GetHasCountry() bool {
	if m != nil {
		return m.HasCountry
	}
	return false
}

func (m *TemplateConfig) GetHasBrandSiteModules() bool {
	if m != nil {
		return m.HasBrandSiteModules
	}
	return false
}

func (m *TemplateConfig) GetHasDemand() bool {
	if m != nil {
		return m.HasDemand
	}
	return false
}

func (m *TemplateConfig) GetHasContact() bool {
	if m != nil {
		return m.HasContact
	}
	return false
}

func (m *TemplateConfig) GetHasSinglePageCustomFunctions() bool {
	if m != nil {
		return m.HasSinglePageCustomFunctions
	}
	return false
}

func (m *TemplateConfig) GetHasBrandSiteCustomFunctions() bool {
	if m != nil {
		return m.HasBrandSiteCustomFunctions
	}
	return false
}

func (m *TemplateConfig) GetHasMallCustomFunctions() bool {
	if m != nil {
		return m.HasMallCustomFunctions
	}
	return false
}

func (m *TemplateConfig) GetHasAppCustomFunctions() bool {
	if m != nil {
		return m.HasAppCustomFunctions
	}
	return false
}

func (m *TemplateConfig) GetHasSinglePageProduct() bool {
	if m != nil {
		return m.HasSinglePageProduct
	}
	return false
}

func (m *TemplateConfig) GetHasSinglePageMarkingTimeCount() bool {
	if m != nil {
		return m.HasSinglePageMarkingTimeCount
	}
	return false
}

func (m *TemplateConfig) GetHasSinglePageMarkingGroupPurchase() bool {
	if m != nil {
		return m.HasSinglePageMarkingGroupPurchase
	}
	return false
}

func (m *TemplateConfig) GetHasSinglePageMarkingFullReduction() bool {
	if m != nil {
		return m.HasSinglePageMarkingFullReduction
	}
	return false
}

func (m *TemplateConfig) GetHasSinglePageMarkingJudgement() bool {
	if m != nil {
		return m.HasSinglePageMarkingJudgement
	}
	return false
}

func (m *TemplateConfig) GetHasLanguage() bool {
	if m != nil {
		return m.HasLanguage
	}
	return false
}

func (m *TemplateConfig) GetHasCurrency() bool {
	if m != nil {
		return m.HasCurrency
	}
	return false
}

func (m *TemplateConfig) GetHasDomains() bool {
	if m != nil {
		return m.HasDomains
	}
	return false
}

func init() {
	proto.RegisterType((*SimpleResponse)(nil), "solution.SimpleResponse")
	proto.RegisterType((*SolutionListRequest)(nil), "solution.SolutionListRequest")
	proto.RegisterType((*SolutionListResponse)(nil), "solution.SolutionListResponse")
	proto.RegisterType((*SolutionDetailRequest)(nil), "solution.SolutionDetailRequest")
	proto.RegisterType((*SolutionDetailResponse)(nil), "solution.SolutionDetailResponse")
	proto.RegisterType((*SolutionSaveOrUpdateRequest)(nil), "solution.SolutionSaveOrUpdateRequest")
	proto.RegisterType((*SolutionTemplateListRequest)(nil), "solution.SolutionTemplateListRequest")
	proto.RegisterType((*SolutionTemplateListResponse)(nil), "solution.SolutionTemplateListResponse")
	proto.RegisterType((*SolutionTemplateDetailRequest)(nil), "solution.SolutionTemplateDetailRequest")
	proto.RegisterType((*SolutionTemplateDetailResponse)(nil), "solution.SolutionTemplateDetailResponse")
	proto.RegisterType((*SolutionListRequestData)(nil), "solution.SolutionListRequestData")
	proto.RegisterType((*SolutionDetailRequestData)(nil), "solution.SolutionDetailRequestData")
	proto.RegisterType((*SolutionTemplateListRequestData)(nil), "solution.SolutionTemplateListRequestData")
	proto.RegisterType((*SolutionListResponseData)(nil), "solution.SolutionListResponseData")
	proto.RegisterType((*SolutionTemplateListResponseData)(nil), "solution.SolutionTemplateListResponseData")
	proto.RegisterType((*SolutionTemplateDetailRequestData)(nil), "solution.SolutionTemplateDetailRequestData")
	proto.RegisterType((*Solution)(nil), "solution.Solution")
	proto.RegisterType((*Domain)(nil), "solution.Domain")
	proto.RegisterType((*SinglePageConfig)(nil), "solution.SinglePageConfig")
	proto.RegisterType((*MarkingConfig)(nil), "solution.MarkingConfig")
	proto.RegisterType((*TimeCount)(nil), "solution.TimeCount")
	proto.RegisterType((*GroupPurchase)(nil), "solution.GroupPurchase")
	proto.RegisterType((*FullReduction)(nil), "solution.FullReduction")
	proto.RegisterType((*Template)(nil), "solution.Template")
	proto.RegisterType((*TemplateConfig)(nil), "solution.TemplateConfig")
}

func init() {
	proto.RegisterFile("solution/solution.proto", fileDescriptor_0797e02bd350d629)
}

var fileDescriptor_0797e02bd350d629 = []byte{
	// 1601 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x58, 0xcd, 0x72, 0xdb, 0x46,
	0x12, 0x2e, 0x8a, 0xfa, 0x21, 0x5b, 0x96, 0x2c, 0x8d, 0x64, 0x09, 0xa6, 0x65, 0x99, 0xe6, 0xd6,
	0x6a, 0xb9, 0xf6, 0x96, 0xed, 0x95, 0xd7, 0xde, 0xad, 0xda, 0xf2, 0xee, 0xda, 0x52, 0xc9, 0x25,
	0x97, 0xbc, 0x56, 0x40, 0xe5, 0x92, 0x9c, 0x46, 0xc0, 0x88, 0x44, 0x0c, 0x60, 0x10, 0x0c, 0xa0,
	0x14, 0xef, 0x79, 0x89, 0xdc, 0x72, 0xc8, 0x29, 0xa7, 0x1c, 0xfc, 0x1c, 0x39, 0xe4, 0x01, 0xf2,
	0x16, 0xb9, 0xa7, 0xa6, 0x67, 0x00, 0x62, 0x00, 0x50, 0xb4, 0xab, 0xa2, 0x13, 0x31, 0x5f, 0x7f,
	0xd3, 0xd3, 0xdd, 0xd3, 0xd3, 0x3d, 0x1c, 0xd8, 0x16, 0xdc, 0x4f, 0x13, 0x8f, 0x87, 0x8f, 0xb3,
	0x8f, 0x47, 0x51, 0xcc, 0x13, 0x4e, 0x5a, 0xd9, 0xb8, 0xf7, 0x1c, 0x56, 0x07, 0x5e, 0x10, 0xf9,
	0xcc, 0x66, 0x22, 0xe2, 0xa1, 0x60, 0x84, 0xc0, 0xbc, 0xc3, 0x5d, 0x66, 0x35, 0xba, 0x8d, 0xfe,
	0x82, 0x8d, 0xdf, 0x64, 0x0d, 0x9a, 0x81, 0x18, 0x5a, 0x73, 0xdd, 0x46, 0xbf, 0x6d, 0xcb, 0xcf,
	0xde, 0xf7, 0x0d, 0xd8, 0x18, 0x68, 0x25, 0x27, 0x9e, 0x48, 0x6c, 0xf6, 0x75, 0xca, 0x44, 0x42,
	0xb6, 0x60, 0x51, 0xf0, 0x34, 0x76, 0xd4, 0xfc, 0xb6, 0xad, 0x47, 0x64, 0x07, 0xda, 0x0e, 0x0f,
	0x22, 0x1a, 0x8e, 0x8f, 0x5d, 0xad, 0x67, 0x02, 0x48, 0x29, 0x75, 0x1c, 0x9e, 0x86, 0xc9, 0xb1,
	0x6b, 0x35, 0x95, 0x34, 0x07, 0xc8, 0x33, 0x98, 0x77, 0x69, 0x42, 0xad, 0xf9, 0x6e, 0xa3, 0xbf,
	0xbc, 0x7f, 0xff, 0x51, 0xee, 0x4c, 0x8d, 0x01, 0x87, 0x34, 0xa1, 0x36, 0xd2, 0x7b, 0x09, 0x6c,
	0x9a, 0x84, 0x4f, 0x71, 0x90, 0x3c, 0xd7, 0x8b, 0x36, 0x71, 0xd1, 0xde, 0xb4, 0x45, 0x95, 0xce,
	0xc2, 0xaa, 0x3f, 0x34, 0xe0, 0x56, 0x46, 0x39, 0x64, 0x09, 0xf5, 0xfc, 0xeb, 0x0c, 0xcd, 0x3f,
	0x8d, 0xd0, 0xfc, 0xa9, 0x6a, 0xa5, 0x61, 0x42, 0xc1, 0xcc, 0x0b, 0xd8, 0x2a, 0x53, 0x3e, 0x29,
	0x3c, 0x7b, 0x46, 0x78, 0x48, 0x75, 0x61, 0xbd, 0xce, 0x77, 0x0d, 0xb8, 0x93, 0x41, 0x03, 0x7a,
	0xc9, 0xde, 0xc5, 0x9f, 0x47, 0x2e, 0x4d, 0xd8, 0x75, 0x06, 0x65, 0xcf, 0x08, 0xca, 0x74, 0xdb,
	0x7e, 0x2a, 0xd8, 0x76, 0xc6, 0x82, 0xc8, 0xa7, 0x09, 0xbb, 0xee, 0x5c, 0x7e, 0x61, 0xd8, 0xf6,
	0xd7, 0xaa, 0x6d, 0x35, 0x86, 0x14, 0xb6, 0xed, 0xdb, 0x06, 0xec, 0xd4, 0x33, 0x3f, 0x69, 0xf7,
	0xfe, 0x63, 0xec, 0xde, 0x83, 0x59, 0x56, 0x54, 0x92, 0xfc, 0x43, 0x03, 0xee, 0x96, 0xa9, 0xd7,
	0x9f, 0xec, 0xff, 0x35, 0x62, 0xf7, 0x70, 0xba, 0xd5, 0xd3, 0x92, 0x3e, 0x84, 0xdd, 0x69, 0xd4,
	0x3f, 0x26, 0xf9, 0x33, 0xad, 0x7a, 0xbd, 0x7f, 0xc3, 0xf6, 0x94, 0x12, 0x45, 0xba, 0xb0, 0x9c,
	0xcd, 0x3a, 0x76, 0x85, 0xd5, 0xe8, 0x36, 0xfb, 0x6d, 0xbb, 0x08, 0xf5, 0x1e, 0xc2, 0xed, 0xa9,
	0x87, 0x98, 0xac, 0xc2, 0x9c, 0xe7, 0xea, 0xd0, 0xce, 0x79, 0x6e, 0xef, 0x19, 0xdc, 0x9b, 0x91,
	0x40, 0xd2, 0xb5, 0x64, 0x1c, 0x65, 0xfb, 0x81, 0xdf, 0xbd, 0x43, 0xb0, 0xa6, 0x95, 0x33, 0xd2,
	0x87, 0x05, 0x2f, 0x61, 0x81, 0xb2, 0xad, 0xfe, 0x18, 0x29, 0x42, 0xef, 0x04, 0xba, 0xb3, 0xf2,
	0xe6, 0x0a, 0x6d, 0x79, 0xcc, 0xb4, 0xb6, 0xa7, 0x70, 0x7f, 0xe6, 0x7e, 0x56, 0xfc, 0xff, 0x71,
	0x09, 0x5a, 0xd9, 0xac, 0xb2, 0x50, 0x8e, 0x43, 0xae, 0xf7, 0x6f, 0x2e, 0xe4, 0x66, 0x0e, 0x36,
	0xcb, 0x39, 0x48, 0x60, 0x3e, 0xa4, 0x01, 0xc3, 0x2c, 0x6b, 0xdb, 0xf8, 0x2d, 0x67, 0x78, 0x61,
	0xc8, 0xe2, 0xff, 0x4b, 0xc1, 0x82, 0x9a, 0x91, 0x03, 0x79, 0x64, 0x17, 0x27, 0x91, 0x25, 0x0f,
	0x60, 0xc9, 0xe5, 0x01, 0xf5, 0x42, 0x61, 0x2d, 0xa1, 0xc7, 0x6b, 0x13, 0x8f, 0x0f, 0x51, 0x60,
	0x67, 0x04, 0x79, 0x56, 0x2e, 0x3d, 0xf6, 0xcd, 0xb1, 0x6b, 0xb5, 0xd4, 0x59, 0x51, 0x23, 0xf2,
	0x08, 0x48, 0xc0, 0xcf, 0x3d, 0x9f, 0x9d, 0xc6, 0x0c, 0xa1, 0x80, 0x0e, 0x99, 0xd5, 0x46, 0x4e,
	0x8d, 0x84, 0xec, 0xc1, 0x6a, 0xe4, 0x18, 0x5c, 0x40, 0x6e, 0x09, 0x95, 0xde, 0x24, 0xa3, 0x34,
	0x38, 0x0f, 0xa9, 0xe7, 0x5b, 0xcb, 0xca, 0x9b, 0x1c, 0x20, 0xbb, 0x00, 0x89, 0x8e, 0xfb, 0xb1,
	0x6b, 0xdd, 0x40, 0x71, 0x01, 0x21, 0x3d, 0xb8, 0x11, 0xd1, 0x71, 0xc0, 0xc2, 0xe4, 0x6c, 0x1c,
	0x31, 0x61, 0xad, 0x60, 0xea, 0x1a, 0x18, 0xf9, 0x1b, 0xac, 0x2b, 0xe7, 0x0e, 0x58, 0x9c, 0x78,
	0x17, 0x9e, 0x43, 0x13, 0x66, 0xad, 0xa2, 0xaa, 0xaa, 0x80, 0x6c, 0xc2, 0x82, 0x27, 0x06, 0x83,
	0x13, 0xeb, 0x66, 0xb7, 0xd1, 0x6f, 0xd9, 0x6a, 0x20, 0xa3, 0xea, 0xf3, 0x21, 0xb7, 0xd6, 0x54,
	0x54, 0xe5, 0x37, 0x56, 0x95, 0x84, 0x26, 0xa9, 0xb0, 0xd6, 0x75, 0x55, 0xc1, 0x11, 0xe9, 0x40,
	0xcb, 0xa7, 0xe1, 0x30, 0x95, 0x3e, 0x13, 0x94, 0xe4, 0x63, 0x69, 0xaf, 0x93, 0xc6, 0x31, 0x0b,
	0x9d, 0xf1, 0x81, 0x3c, 0xda, 0x1b, 0x28, 0x37, 0x30, 0x19, 0xb9, 0x6c, 0x3c, 0x18, 0x07, 0xe7,
	0xdc, 0xb7, 0x36, 0x55, 0xe4, 0x4c, 0x54, 0xc6, 0xc6, 0x89, 0x19, 0x4d, 0xd8, 0x99, 0x17, 0x30,
	0xeb, 0x96, 0x8a, 0xcd, 0x04, 0x91, 0xf2, 0x14, 0xdb, 0x1b, 0xca, 0xb7, 0x94, 0x7c, 0x82, 0x90,
	0x7f, 0xc0, 0x2d, 0x19, 0xc6, 0x0b, 0x1e, 0x07, 0x79, 0x8e, 0xf3, 0xf7, 0x2c, 0xb4, 0xb6, 0x91,
	0x5a, 0x2f, 0x94, 0x79, 0x50, 0x16, 0x1c, 0xbb, 0x96, 0xa5, 0xf2, 0xa0, 0x2a, 0x21, 0xfb, 0xb0,
	0x59, 0x46, 0x31, 0x71, 0x6f, 0xe3, 0x8c, 0x5a, 0x19, 0xee, 0xaa, 0xc6, 0x91, 0xdb, 0x51, 0x51,
	0x2a, 0x62, 0xe4, 0x08, 0xd6, 0x84, 0x17, 0x0e, 0x7d, 0x76, 0x4a, 0x87, 0xec, 0x80, 0x87, 0x17,
	0xde, 0xd0, 0xba, 0x83, 0x25, 0xb0, 0x53, 0x28, 0x0e, 0x25, 0x86, 0x5d, 0x99, 0xd3, 0xfb, 0x17,
	0x2c, 0xaa, 0x23, 0x20, 0xf7, 0x53, 0xa5, 0x43, 0xd6, 0x25, 0xdc, 0x1c, 0xd7, 0xfb, 0x3c, 0x57,
	0xdc, 0x67, 0x79, 0x9b, 0x58, 0x2b, 0x2f, 0x20, 0xd3, 0x39, 0x8a, 0xb9, 0x9b, 0x3a, 0xb2, 0x69,
	0x28, 0x3d, 0x13, 0x80, 0xf4, 0xe1, 0xa6, 0x93, 0x8a, 0x84, 0x07, 0x47, 0x69, 0xe8, 0x48, 0x0b,
	0xa5, 0x4e, 0x99, 0xb1, 0x65, 0x98, 0xbc, 0x80, 0x95, 0x80, 0xc6, 0xef, 0xbd, 0x70, 0xa8, 0x7d,
	0x53, 0xe5, 0x7d, 0x7b, 0xe2, 0xdb, 0xdb, 0xa2, 0xd8, 0x36, 0xd9, 0xbd, 0x5f, 0x1b, 0xb0, 0x62,
	0x10, 0xc8, 0xdf, 0xa1, 0x9d, 0x78, 0x01, 0x3b, 0x90, 0xed, 0x0b, 0x0d, 0x5b, 0xde, 0xdf, 0x28,
	0xd4, 0xbd, 0x4c, 0x64, 0x4f, 0x58, 0xd2, 0x86, 0x61, 0xcc, 0xd3, 0xe8, 0x34, 0x8d, 0x9d, 0x11,
	0x15, 0x0c, 0xfd, 0x37, 0x6c, 0x78, 0x5d, 0x14, 0xdb, 0x26, 0x5b, 0x4e, 0xbf, 0x48, 0x7d, 0xdf,
	0x66, 0xd2, 0x79, 0x8f, 0x87, 0x55, 0x17, 0x8e, 0x8a, 0x62, 0xdb, 0x64, 0xcb, 0x48, 0x7e, 0x95,
	0xba, 0x43, 0x26, 0x0f, 0xb2, 0xae, 0x7f, 0x13, 0xa0, 0xf7, 0x5b, 0x03, 0xda, 0xb9, 0xd1, 0xf2,
	0xc8, 0xb8, 0x69, 0x4c, 0xf1, 0x5e, 0xc7, 0x1c, 0x1e, 0xaa, 0xd0, 0x37, 0xed, 0x12, 0x8a, 0x89,
	0xa5, 0x36, 0xe3, 0x8c, 0x27, 0xd4, 0x47, 0x87, 0x9a, 0xb6, 0x81, 0xc9, 0x66, 0xa8, 0xc7, 0x03,
	0xee, 0xab, 0x92, 0xdc, 0xb4, 0x8b, 0x90, 0x5c, 0x6d, 0xc4, 0xd3, 0x58, 0x9c, 0xf1, 0x97, 0xae,
	0x8b, 0xa4, 0x79, 0xb5, 0x9a, 0x89, 0x92, 0x07, 0xb0, 0x96, 0x6b, 0xce, 0x98, 0x0b, 0xc8, 0xac,
	0xe0, 0x05, 0x9d, 0x36, 0x73, 0xf8, 0x25, 0x8b, 0xb1, 0x80, 0x4f, 0x74, 0x6a, 0xb4, 0xf7, 0x1a,
	0x56, 0x8c, 0xa0, 0x13, 0x0b, 0x96, 0x02, 0x16, 0x9c, 0xb3, 0x58, 0x68, 0x9f, 0xb3, 0xa1, 0x0c,
	0x60, 0x9c, 0xc7, 0x5e, 0x79, 0x3a, 0x01, 0x7a, 0x5f, 0xc2, 0x8a, 0x11, 0x7e, 0x59, 0x26, 0x69,
	0x20, 0xa3, 0x29, 0x17, 0xcb, 0xa6, 0x29, 0x95, 0x55, 0xc1, 0x0c, 0xe5, 0xbf, 0xcc, 0x41, 0x2b,
	0xeb, 0x97, 0x95, 0x0e, 0x98, 0xf5, 0xb4, 0xb9, 0x42, 0x4f, 0x23, 0x30, 0xef, 0x32, 0xe1, 0xe8,
	0x06, 0x88, 0xdf, 0x79, 0x27, 0x9b, 0x2f, 0x74, 0xb2, 0x6a, 0x57, 0x59, 0xa8, 0xed, 0x2a, 0xf5,
	0xdd, 0x6a, 0x71, 0x6a, 0xb7, 0x32, 0xba, 0xd0, 0x52, 0xb9, 0x0b, 0xed, 0x40, 0xdb, 0xf7, 0x44,
	0xa2, 0x94, 0xa8, 0xb6, 0x38, 0x01, 0x50, 0xaa, 0xeb, 0xbb, 0xb0, 0xda, 0x78, 0x9c, 0x27, 0x80,
	0xac, 0x1e, 0x9e, 0x38, 0x8a, 0x99, 0xea, 0x7f, 0x2d, 0x5b, 0x8f, 0xc8, 0x13, 0x58, 0x74, 0xd4,
	0xc9, 0x5e, 0xc6, 0x63, 0x61, 0x55, 0x2f, 0x21, 0xfa, 0x68, 0x6b, 0x5e, 0xef, 0xc3, 0x12, 0xac,
	0x9a, 0x22, 0xb9, 0xf9, 0x23, 0x2a, 0x4e, 0x64, 0x67, 0x6a, 0xa0, 0xf6, 0x6c, 0x28, 0x8d, 0x1a,
	0x51, 0xa1, 0x2a, 0x1b, 0x46, 0xba, 0x65, 0x4f, 0x00, 0xcc, 0x36, 0x2a, 0x4e, 0x27, 0x5d, 0x12,
	0x03, 0xdf, 0xb2, 0x4b, 0xa8, 0x6c, 0x21, 0x23, 0x2a, 0xf0, 0x8c, 0xc5, 0x63, 0xdc, 0x88, 0x96,
	0x5d, 0x40, 0xc8, 0x13, 0xd8, 0x18, 0x51, 0xf1, 0x2a, 0xa6, 0xa1, 0x3b, 0xf0, 0x12, 0xf6, 0x96,
	0xbb, 0xa9, 0xcf, 0x04, 0xee, 0x49, 0xcb, 0xae, 0x13, 0x65, 0x76, 0xb1, 0x80, 0x86, 0x2e, 0xee,
	0x87, 0xb6, 0x0b, 0x81, 0x7c, 0xbd, 0x30, 0xa1, 0x4e, 0x82, 0xfb, 0x90, 0xad, 0x87, 0x08, 0x79,
	0x05, 0x3b, 0x23, 0x2a, 0x0a, 0x45, 0xb7, 0x54, 0x4c, 0x5b, 0x38, 0xe3, 0x4a, 0x0e, 0xf9, 0x1f,
	0xdc, 0x29, 0x1a, 0x56, 0x56, 0xd1, 0x46, 0x15, 0x57, 0x51, 0xc8, 0x73, 0xd8, 0x1a, 0x51, 0xf1,
	0x96, 0xfa, 0x7e, 0x79, 0xb2, 0xda, 0xe2, 0x29, 0x52, 0xd9, 0x70, 0x47, 0x54, 0xbc, 0x8c, 0xa2,
	0xf2, 0xb4, 0x65, 0x9c, 0x56, 0x2f, 0x94, 0x0d, 0xd4, 0xf0, 0xe7, 0x54, 0x95, 0x0e, 0xbc, 0x0c,
	0xb5, 0xec, 0x5a, 0x19, 0x39, 0x84, 0xbb, 0x06, 0xae, 0x5b, 0x41, 0x5e, 0x30, 0xad, 0x15, 0x9c,
	0x7c, 0x35, 0x89, 0x9c, 0xc0, 0xfd, 0x3a, 0x82, 0x51, 0x7f, 0xf0, 0x22, 0xd5, 0xb2, 0x67, 0x13,
	0xa7, 0x69, 0x33, 0x8a, 0x90, 0xbe, 0x74, 0xcd, 0x26, 0x4e, 0xf3, 0xf0, 0x4d, 0xde, 0x31, 0xd6,
	0xa6, 0x7b, 0x98, 0x93, 0x64, 0xad, 0x97, 0x07, 0x26, 0xbb, 0xad, 0xad, 0xe3, 0x9c, 0x22, 0xa4,
	0x19, 0x07, 0xfa, 0xe6, 0x85, 0xf7, 0x39, 0xc5, 0xc8, 0x20, 0x9d, 0xb3, 0x87, 0xfa, 0x7e, 0xbd,
	0x91, 0xe7, 0xac, 0x46, 0xf6, 0x7f, 0x6e, 0xc2, 0xcd, 0xfc, 0xd1, 0x81, 0xc5, 0x97, 0x9e, 0xc3,
	0xc8, 0x1b, 0x68, 0x7f, 0x96, 0xb2, 0x78, 0x2c, 0xff, 0x99, 0x90, 0xbb, 0x57, 0xbe, 0x21, 0x75,
	0x76, 0xaf, 0x7e, 0xed, 0x21, 0xa7, 0xb0, 0x8c, 0xba, 0xd4, 0xff, 0x12, 0x72, 0x6f, 0xc6, 0xb3,
	0x4b, 0xa7, 0x3b, 0x9d, 0xa0, 0x35, 0xbe, 0x83, 0x1b, 0xc5, 0xd7, 0x11, 0xf2, 0xe7, 0xea, 0x8c,
	0x9a, 0xd7, 0x93, 0x8e, 0x55, 0xbc, 0x77, 0x19, 0xaf, 0x78, 0xe7, 0xb0, 0x8e, 0x26, 0x16, 0xff,
	0x90, 0xd5, 0x69, 0xad, 0xf9, 0xb7, 0xd8, 0xd9, 0xfb, 0xb8, 0xf7, 0x00, 0x32, 0x82, 0x0d, 0x63,
	0x0d, 0x1d, 0x8e, 0xbf, 0x7c, 0xe4, 0x1f, 0xf3, 0x4e, 0x7f, 0x36, 0x51, 0xad, 0xf4, 0x6a, 0xf7,
	0x8b, 0x1d, 0x1a, 0x45, 0x8f, 0xf1, 0xf1, 0xd2, 0xd1, 0x3f, 0xdc, 0xcf, 0x5f, 0x35, 0xcf, 0x17,
	0x11, 0x7a, 0xfa, 0x7b, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc0, 0x8c, 0x11, 0xa1, 0xf1, 0x14, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SolutionServiceClient is the client API for SolutionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SolutionServiceClient interface {
	QueryList(ctx context.Context, in *SolutionListRequest, opts ...grpc.CallOption) (*SolutionListResponse, error)
	QueryDetail(ctx context.Context, in *SolutionDetailRequest, opts ...grpc.CallOption) (*SolutionDetailResponse, error)
	SaveOrUpdate(ctx context.Context, in *SolutionSaveOrUpdateRequest, opts ...grpc.CallOption) (*SimpleResponse, error)
	QueryTemplateList(ctx context.Context, in *SolutionTemplateListRequest, opts ...grpc.CallOption) (*SolutionTemplateListResponse, error)
	QueryTemplateDetail(ctx context.Context, in *SolutionTemplateDetailRequest, opts ...grpc.CallOption) (*SolutionTemplateDetailResponse, error)
}

type solutionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSolutionServiceClient(cc grpc.ClientConnInterface) SolutionServiceClient {
	return &solutionServiceClient{cc}
}

func (c *solutionServiceClient) QueryList(ctx context.Context, in *SolutionListRequest, opts ...grpc.CallOption) (*SolutionListResponse, error) {
	out := new(SolutionListResponse)
	err := c.cc.Invoke(ctx, "/solution.SolutionService/QueryList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *solutionServiceClient) QueryDetail(ctx context.Context, in *SolutionDetailRequest, opts ...grpc.CallOption) (*SolutionDetailResponse, error) {
	out := new(SolutionDetailResponse)
	err := c.cc.Invoke(ctx, "/solution.SolutionService/QueryDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *solutionServiceClient) SaveOrUpdate(ctx context.Context, in *SolutionSaveOrUpdateRequest, opts ...grpc.CallOption) (*SimpleResponse, error) {
	out := new(SimpleResponse)
	err := c.cc.Invoke(ctx, "/solution.SolutionService/SaveOrUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *solutionServiceClient) QueryTemplateList(ctx context.Context, in *SolutionTemplateListRequest, opts ...grpc.CallOption) (*SolutionTemplateListResponse, error) {
	out := new(SolutionTemplateListResponse)
	err := c.cc.Invoke(ctx, "/solution.SolutionService/QueryTemplateList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *solutionServiceClient) QueryTemplateDetail(ctx context.Context, in *SolutionTemplateDetailRequest, opts ...grpc.CallOption) (*SolutionTemplateDetailResponse, error) {
	out := new(SolutionTemplateDetailResponse)
	err := c.cc.Invoke(ctx, "/solution.SolutionService/QueryTemplateDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SolutionServiceServer is the server API for SolutionService service.
type SolutionServiceServer interface {
	QueryList(context.Context, *SolutionListRequest) (*SolutionListResponse, error)
	QueryDetail(context.Context, *SolutionDetailRequest) (*SolutionDetailResponse, error)
	SaveOrUpdate(context.Context, *SolutionSaveOrUpdateRequest) (*SimpleResponse, error)
	QueryTemplateList(context.Context, *SolutionTemplateListRequest) (*SolutionTemplateListResponse, error)
	QueryTemplateDetail(context.Context, *SolutionTemplateDetailRequest) (*SolutionTemplateDetailResponse, error)
}

// UnimplementedSolutionServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSolutionServiceServer struct {
}

func (*UnimplementedSolutionServiceServer) QueryList(ctx context.Context, req *SolutionListRequest) (*SolutionListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryList not implemented")
}
func (*UnimplementedSolutionServiceServer) QueryDetail(ctx context.Context, req *SolutionDetailRequest) (*SolutionDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryDetail not implemented")
}
func (*UnimplementedSolutionServiceServer) SaveOrUpdate(ctx context.Context, req *SolutionSaveOrUpdateRequest) (*SimpleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveOrUpdate not implemented")
}
func (*UnimplementedSolutionServiceServer) QueryTemplateList(ctx context.Context, req *SolutionTemplateListRequest) (*SolutionTemplateListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryTemplateList not implemented")
}
func (*UnimplementedSolutionServiceServer) QueryTemplateDetail(ctx context.Context, req *SolutionTemplateDetailRequest) (*SolutionTemplateDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryTemplateDetail not implemented")
}

func RegisterSolutionServiceServer(s *grpc.Server, srv SolutionServiceServer) {
	s.RegisterService(&_SolutionService_serviceDesc, srv)
}

func _SolutionService_QueryList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SolutionListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SolutionServiceServer).QueryList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/solution.SolutionService/QueryList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SolutionServiceServer).QueryList(ctx, req.(*SolutionListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SolutionService_QueryDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SolutionDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SolutionServiceServer).QueryDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/solution.SolutionService/QueryDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SolutionServiceServer).QueryDetail(ctx, req.(*SolutionDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SolutionService_SaveOrUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SolutionSaveOrUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SolutionServiceServer).SaveOrUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/solution.SolutionService/SaveOrUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SolutionServiceServer).SaveOrUpdate(ctx, req.(*SolutionSaveOrUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SolutionService_QueryTemplateList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SolutionTemplateListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SolutionServiceServer).QueryTemplateList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/solution.SolutionService/QueryTemplateList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SolutionServiceServer).QueryTemplateList(ctx, req.(*SolutionTemplateListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SolutionService_QueryTemplateDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SolutionTemplateDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SolutionServiceServer).QueryTemplateDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/solution.SolutionService/QueryTemplateDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SolutionServiceServer).QueryTemplateDetail(ctx, req.(*SolutionTemplateDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SolutionService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "solution.SolutionService",
	HandlerType: (*SolutionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryList",
			Handler:    _SolutionService_QueryList_Handler,
		},
		{
			MethodName: "QueryDetail",
			Handler:    _SolutionService_QueryDetail_Handler,
		},
		{
			MethodName: "SaveOrUpdate",
			Handler:    _SolutionService_SaveOrUpdate_Handler,
		},
		{
			MethodName: "QueryTemplateList",
			Handler:    _SolutionService_QueryTemplateList_Handler,
		},
		{
			MethodName: "QueryTemplateDetail",
			Handler:    _SolutionService_QueryTemplateDetail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "solution/solution.proto",
}
