// Code generated by protoc-gen-go. DO NOT EDIT.
// source: workticket/common_ticket.proto

package workticket

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type WorkTicketResp struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WorkTicketResp) Reset()         { *m = WorkTicketResp{} }
func (m *WorkTicketResp) String() string { return proto.CompactTextString(m) }
func (*WorkTicketResp) ProtoMessage()    {}
func (*WorkTicketResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2007927c8e77617, []int{0}
}

func (m *WorkTicketResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkTicketResp.Unmarshal(m, b)
}
func (m *WorkTicketResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkTicketResp.Marshal(b, m, deterministic)
}
func (m *WorkTicketResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkTicketResp.Merge(m, src)
}
func (m *WorkTicketResp) XXX_Size() int {
	return xxx_messageInfo_WorkTicketResp.Size(m)
}
func (m *WorkTicketResp) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkTicketResp.DiscardUnknown(m)
}

var xxx_messageInfo_WorkTicketResp proto.InternalMessageInfo

func (m *WorkTicketResp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *WorkTicketResp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*WorkTicketResp)(nil), "workticket.WorkTicketResp")
}

func init() {
	proto.RegisterFile("workticket/common_ticket.proto", fileDescriptor_a2007927c8e77617)
}

var fileDescriptor_a2007927c8e77617 = []byte{
	// 126 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2b, 0xcf, 0x2f, 0xca,
	0x2e, 0xc9, 0x4c, 0xce, 0x4e, 0x2d, 0xd1, 0x4f, 0xce, 0xcf, 0xcd, 0xcd, 0xcf, 0x8b, 0x87, 0xf0,
	0xf4, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85, 0xb8, 0x10, 0xf2, 0x4a, 0x66, 0x5c, 0x7c, 0xe1, 0xf9,
	0x45, 0xd9, 0x21, 0x60, 0x5e, 0x50, 0x6a, 0x71, 0x81, 0x90, 0x10, 0x17, 0x4b, 0x72, 0x7e, 0x4a,
	0xaa, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x6b, 0x10, 0x98, 0x2d, 0x24, 0xc0, 0xc5, 0x9c, 0x5b, 0x9c,
	0x2e, 0xc1, 0xa4, 0xc0, 0xa8, 0xc1, 0x19, 0x04, 0x62, 0x3a, 0x29, 0x44, 0xc9, 0x25, 0x16, 0x14,
	0xe8, 0x83, 0x0d, 0x4c, 0x86, 0x52, 0xf9, 0x39, 0xfa, 0x08, 0x93, 0x93, 0xd8, 0xc0, 0x82, 0xc6,
	0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0d, 0xfb, 0x10, 0x73, 0x8e, 0x00, 0x00, 0x00,
}
